// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW976_zECqcZhWxojgP9ZpAO9vH2LQ2cs',
    appId: '1:877206198583:web:666adc5caeaa117453a2b2',
    messagingSenderId: '877206198583',
    projectId: 'smartfarmx-221',
    authDomain: 'smartfarmx-221.firebaseapp.com',
    storageBucket: 'smartfarmx-221.firebasestorage.app',
    measurementId: 'G-SDT9HG38T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4PYqDdrnWhuN0fsghstldzSwaogAysA',
    appId: '1:877206198583:android:37a29cd56e705a6f53a2b2',
    messagingSenderId: '877206198583',
    projectId: 'smartfarmx-221',
    storageBucket: 'smartfarmx-221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJgMpY8FDC9w8RC6dhb2KzBEij7Y2ilk',
    appId: '1:877206198583:ios:056949c69fbd398753a2b2',
    messagingSenderId: '877206198583',
    projectId: 'smartfarmx-221',
    storageBucket: 'smartfarmx-221.firebasestorage.app',
    iosBundleId: 'com.example.smartfarmx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJgMpY8FDC9w8RC6dhb2KzBEij7Y2ilk',
    appId: '1:877206198583:ios:056949c69fbd398753a2b2',
    messagingSenderId: '877206198583',
    projectId: 'smartfarmx-221',
    storageBucket: 'smartfarmx-221.firebasestorage.app',
    iosBundleId: 'com.example.smartfarmx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW976_zECqcZhWxojgP9ZpAO9vH2LQ2cs',
    appId: '1:877206198583:web:c8224acf3605877b53a2b2',
    messagingSenderId: '877206198583',
    projectId: 'smartfarmx-221',
    authDomain: 'smartfarmx-221.firebaseapp.com',
    storageBucket: 'smartfarmx-221.firebasestorage.app',
    measurementId: 'G-D53QC2GW08',
  );
}
